# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: install reprepo
        run: |
          sudo apt update
          sudo apt -y install reprepro

      - name: Checkout
        uses: actions/checkout@v4

      # Restore the cache before generating the site
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: repository
          key: repository-cache-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            repository-cache-${{ github.ref }}-
            repository-cache-

      - name: update repository
        run: |
          set -x -v
          echo "before"
          tree -a repository
          reprepro -V --basedir repository includedeb jammy asterisk22_22.1.1-1_amd64.deb
          reprepro -V --basedir repository includedsc jammy asterisk22_22.1.1-1.dsc
          echo "after"
          tree -a repository
          set +x +v

      # Save the cache after generating the site
      - name: Save repository cache
        uses: actions/cache/save@v4
        with:
          path: repository
          key: repository-cache-${{ github.ref }}-${{ github.run_id }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'repository'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
